// Эмблемы банд — иконки game-icons.net (CC BY 3.0, авторы: Lorc, Delapouite, Skoll, Carl Olsen, Caro Asercion, DarkZaitzev и др.).
// В gangs.emoji хранится `icon:<id>`; старые банды с эмодзи продолжают работать.

export const GANG_EMBLEMS: { id: string; title: string }[] = [
	{ id: 'skull', title: 'Череп' },
	{ id: 'crowned-skull', title: 'Король-череп' },
	{ id: 'pirate', title: 'Пираты' },
	{ id: 'wolf', title: 'Волки' },
	{ id: 'wolf-howl', title: 'Вой' },
	{ id: 'dragon', title: 'Драконы' },
	{ id: 'rat', title: 'Крысы' },
	{ id: 'fist', title: 'Кулак' },
	{ id: 'brass', title: 'Кастет' },
	{ id: 'boxing', title: 'Боксёры' },
	{ id: 'muscle', title: 'Качки' },
	{ id: 'crown', title: 'Корона' },
	{ id: 'jewel-crown', title: 'Короли' },
	{ id: 'dynamite', title: 'Динамит' },
	{ id: 'molotov', title: 'Молотов' },
	{ id: 'chainsaw', title: 'Бензопила' },
	{ id: 'axe', title: 'Топоры' },
	{ id: 'viking', title: 'Викинги' },
	{ id: 'viking-helm', title: 'Шлем' },
	{ id: 'ninja', title: 'Ниндзя' },
	{ id: 'samurai', title: 'Самураи' },
	{ id: 'orc', title: 'Орки' },
	{ id: 'goblin', title: 'Гоблины' },
	{ id: 'ogre', title: 'Огры' },
	{ id: 'devil', title: 'Черти' },
	{ id: 'imp', title: 'Бесы' },
	{ id: 'imp-laugh', title: 'Хохотуны' },
	{ id: 'ghost', title: 'Призраки' },
	{ id: 'vampire', title: 'Вампиры' },
	{ id: 'bat', title: 'Летучки' },
	{ id: 'spider', title: 'Пауки' },
	{ id: 'snake', title: 'Змеи' },
	{ id: 'rattle', title: 'Гремучки' },
	{ id: 'scorpion', title: 'Скорпионы' },
	{ id: 'shark', title: 'Акулы' },
	{ id: 'lion', title: 'Львы' },
	{ id: 'bear', title: 'Медведи' },
	{ id: 'eagle', title: 'Орлы' },
	{ id: 'owl', title: 'Совы' },
	{ id: 'fox', title: 'Лисы' },
	{ id: 'cat', title: 'Коты' },
	{ id: 'bull', title: 'Быки' },
	{ id: 'boar', title: 'Кабаны' },
	{ id: 'rhino', title: 'Носороги' },
	{ id: 'octopus', title: 'Осьминоги' },
	{ id: 'kraken', title: 'Кракены' },
	{ id: 'rex', title: 'Динозавры' },
	{ id: 'unicorn', title: 'Единороги' },
	{ id: 'anchor', title: 'Якорь' },
	{ id: 'trident', title: 'Трезубец' },
	{ id: 'horned', title: 'Рогатые' },
	{ id: 'claw', title: 'Когти' },
	{ id: 'fire', title: 'Огонь' },
	{ id: 'fireball', title: 'Фаербол' },
	{ id: 'lightning', title: 'Молнии' },
	{ id: 'thunder', title: 'Гроза' },
	{ id: 'ufo', title: 'НЛО' },
	{ id: 'alien', title: 'Пришельцы' },
	{ id: 'alien-bug', title: 'Жуки' },
	{ id: 'robot', title: 'Роботы' },
	{ id: 'rocket', title: 'Ракета' },
	{ id: 'joystick', title: 'Джойстик' },
	{ id: 'gamepad', title: 'Геймеры' },
	{ id: 'dice', title: 'Д20' },
	{ id: 'dice-fire', title: 'Игроки' },
	{ id: 'jester', title: 'Шуты' },
	{ id: 'duck', title: 'Утки' },
	{ id: 'plunger', title: 'Вантуз' },
	{ id: 'potato', title: 'Картошка' },
	{ id: 'cactus', title: 'Кактусы' },
	{ id: 'mushroom', title: 'Грибы' },
	{ id: 'burger', title: 'Бургеры' },
	{ id: 'donut', title: 'Пончики' },
	{ id: 'pizza', title: 'Пицца' },
	{ id: 'cheese', title: 'Сырники' },
	{ id: 'banana', title: 'Бананы' },
	{ id: 'taco', title: 'Тако' },
	{ id: 'hotdog', title: 'Хот-доги' },
	{ id: 'fries', title: 'Фри' },
	{ id: 'sunglasses', title: 'Крутые' },
	{ id: 'tophat', title: 'Джентльмены' },
	{ id: 'cowboy', title: 'Ковбои' },
	{ id: 'bandit', title: 'Бандиты' },
	{ id: 'hooded', title: 'Тени' },
	{ id: 'handcuffs', title: 'Наручники' },
	{ id: 'prisoner', title: 'Зэки' },
	{ id: 'bank', title: 'Банк' },
	{ id: 'money', title: 'Бабки' },
	{ id: 'cash', title: 'Кэш' },
	{ id: 'diamond', title: 'Бриллиант' },
	{ id: 'gold', title: 'Золото' },
	{ id: 'barrel', title: 'Бочка' },
	{ id: 'cannon', title: 'Пушка' },
	{ id: 'pirate-hat', title: 'Капитаны' },
	{ id: 'revolver', title: 'Револьвер' },
	{ id: 'katana', title: 'Катана' },
	{ id: 'shuriken', title: 'Сюрикены' },
	{ id: 'sword', title: 'Мечи' },
	{ id: 'shield', title: 'Щит' },
	{ id: 'star', title: 'Звезда' },
	{ id: 'star-skull', title: 'Звёзды' },
	{ id: 'moon', title: 'Луна' },
	{ id: 'sun', title: 'Солнце' },
	{ id: 'volcano', title: 'Вулкан' },
	{ id: 'tornado', title: 'Торнадо' },
	{ id: 'meteor', title: 'Метеор' },
	{ id: 'snowflake', title: 'Снежки' },
	{ id: 'nuclear', title: 'Бомба' },
	{ id: 'radio', title: 'Радиация' },
	{ id: 'biohazard', title: 'Биохаз' },
	{ id: 'poison', title: 'Яд' },
	{ id: 'beer', title: 'Пивасик' },
	{ id: 'coffee', title: 'Кофеманы' },
	{ id: 'bee', title: 'Пчёлы' },
	{ id: 'butterfly', title: 'Бабочки' },
	{ id: 'frog', title: 'Лягушки' },
	{ id: 'turtle', title: 'Черепахи' },
	{ id: 'penguin', title: 'Пингвины' },
	{ id: 'rooster', title: 'Петухи' },
	{ id: 'chicken', title: 'Куры' },
	{ id: 'raven', title: 'Вороны' },
	{ id: 'parrot', title: 'Попугаи' },
	{ id: 'rabbit', title: 'Зайцы' },
	{ id: 'piranha', title: 'Пираньи' },
	{ id: 'crab', title: 'Крабы' },
	{ id: 'jellyfish', title: 'Медузы' },
	{ id: 'dolphin', title: 'Дельфины' },
	{ id: 'clover', title: 'Клевер' },
	{ id: 'horseshoe', title: 'Подкова' },
	{ id: 'peace', title: 'Мир' },
	{ id: 'yin', title: 'Инь-ян' },
	{ id: 'heart', title: 'Сердце' },
	{ id: 'fire-axe', title: 'Огненный топор' },
	{ id: 'bomb', title: 'Бомбилы' },
	{ id: 'baseball', title: 'Бита' },
	{ id: 'crowbar', title: 'Фомка' },
	{ id: 'scythe', title: 'Коса' },
	{ id: 'bowling', title: 'Кегли' },
	{ id: 'sunflower', title: 'Подсолнух' },
]

export const GANG_COLORS = ['#BC418A', '#C385F7', '#53ADEF', '#5CC99F', '#78C93C', '#F2C35B', '#F09B38', '#DC605B'] as const
export const DEFAULT_GANG_COLOR = '#C385F7'

export const EMBLEM_PREFIX = 'icon:'

/** 'icon:wolf' -> 'wolf'; для старых эмодзи возвращает null. */
export const emblemIdOf = (value: string | null | undefined): string | null =>
	value && value.startsWith(EMBLEM_PREFIX) ? value.slice(EMBLEM_PREFIX.length) : null

export const isValidEmblem = (value: string) => {
	const id = emblemIdOf(value)
	return id !== null && GANG_EMBLEMS.some((e) => e.id === id)
}
